services:
  mini_fasttrack2_redis:
      container_name: mini_fasttrack2_redis
      image: redis:7.4-alpine
      restart: always
      ports:
      - "${REDIS_PORT}:6379"
      volumes:
        - redis_data:/data
  
volumes:
  redis_data: